[package]
name = "p2psearch"
version = "0.1.0"
authors = ["Ramazan Acar <ramazan.acar@metglobal.com>"]

[dependencies]
futures = "0.1"
hyper = "0.11.6"
tokio-core = "0.1"
serde_json = "1.0"
hyper-tls = "*"
term = "0.4.6"